inherit_gem:
  syntax_tree: config/rubocop.yml

require: rubocop-minitest

AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/BooleanSymbol:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
