name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: build docker image
        run: docker build . -t mya
      - name: run lint
        run: docker run mya bundle exec rake lint
