name: Specs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  specs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: build docker image
        run: docker build . -t mya
      - name: run specs
        run: docker run --entrypoint="" mya bundle exec rake spec
